Repository Semesterproject4/back-end, pull requests merged in 2021-05, with the labels that each got.

#45 7 BatchReportService interface
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchReportService.java
Labels: enhancement

#46 13 Ingredients entity class
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Ingredients.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/IngredientsTest.java
Labels: enhancement

#44 11 Connection entity class
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Connection.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/ConnectionTest.java
Labels: enhancement

#49 15 ScheduledData entity class
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/ScheduledBatch.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/ScheduledBatchTest.java
Labels: enhancement

#51 12 MachineData entity class
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/MachineData.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/MachineDataTest.java
Labels: enhancement

#50 8 MachineService interface
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IMachineService.java
Labels: enhancement

#53 52 Make JavaDoc for IBatchReportService
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchReportService.java
Labels: documentation

#56 19 ScheduleRepository interface
  BrewMesModulesParent/common_repository/pom.xml
  BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/ScheduleRepository.java
Labels: enhancement

#58 Add ConnectionRepository
  BrewMesModulesParent/common_repository/pom.xml
  BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/ConnectionRepository.java
Labels: enhancement

#59 Add ISheduleService
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IScheduleService.java
Labels: enhancement

#62 38 BatchController
  BrewMesModulesParent/api/batch_report.pdf
  BrewMesModulesParent/api/pom.xml
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
  BrewMesModulesParent/batch/pom.xml
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
Labels: enhancement

#66 40-ScheduleController
  BrewMesModulesParent/api/pom.xml
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
  BrewMesModulesParent/api/src/test/java/com/brewmes/api/ScheduleControllerTest.java
  BrewMesModulesParent/common/pom.xml
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/ScheduledBatch.java
Labels: enhancement

#75 26 socketmachinedatacontroller
  BrewMesModulesParent/livedata/pom.xml
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/WebSocketConfig.java
  BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
  BrewMesModulesParent/pom.xml
Labels: enhancement

#78 36 PdfBatchServiceImpl
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfBatchServiceImpl.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
Labels: enhancement

#79 61 BatchGetterImpl
  BrewMesModulesParent/api/batch_report.pdf
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
  BrewMesModulesParent/core/src/main/java/com/brewmes/core/CoreApplication.java
  BrewMesModulesParent/core/src/main/resources/application.properties
Labels: enhancement

#89 60 Remove "required = false" from BatchController
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
Labels: enhancement

#95 Make state on MachineData an object of MachineState enum
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/MachineData.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/MachineDataTest.java
Labels: enhancement

#92 32 MachineServiceImpl
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Connection.java
  BrewMesModulesParent/machine/pom.xml
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/MachineServiceImpl.java
  BrewMesModulesParent/machine/src/test/java/com/brewmes/machine/MachineServiceImplTest.java
Labels: enhancement

#102 27 machinesubscriber
  BrewMesModulesParent/api/pom.xml
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Ingredients.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/MachineData.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/MachineState.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/machinenodes/MachineNodes.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/IngredientsTest.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/MachineDataTest.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/util/MachineStateTest.java
  BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/BatchRepository.java
  BrewMesModulesParent/pom.xml
  BrewMesModulesParent/subscriber/pom.xml
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/MachineSubscriber.java
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
  BrewMesModulesParent/subscriber/src/test/java/com/brewmes/subscriber/MachineSubscriberTest.java
Labels: enhancement

#109 Add optimalSpeed to Products
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/Products.java
Labels: enhancement

#107 85 Remove 'required = false' from the Machine package
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/MachineServiceImpl.java
Labels: enhancement

#105 104 Make Batch use product enum
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PrepareData.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/DashboardBatchServiceImplTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PrepareDataTest.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Batch.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/Products.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/BatchTest.java
  BrewMesModulesParent/common/src/test/java/com/brewmes/common/util/ProductsTest.java
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
Labels: enhancement

#117 Change datatype
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/ScheduledBatch.java
Labels: bug

#115 Add optimal speed to endpoint
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
Labels: enhancement

#121 110 products endpoint does not return response entity with json header
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
Labels: enhancement

#122 113 NullPointerException in MachineService
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
Labels: enhancement

#124 Update websocket access
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/WebSocketConfig.java
Labels: bug

#131 125 Optimisation of pagination
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
Labels: enhancement

#132 130 does autobrewing actually work
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/WebSocketConfig.java
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
  BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/MachineServiceImpl.java
Labels: enhancement

#134 Add access to batch data in liveview
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
  BrewMesModulesParent/common/pom.xml
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
  BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/BatchRepository.java
Labels: enhancement

#147 Fix method capitalization
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
  BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
Labels: enhancement

#145 140 Change the API component annotation from @RestController to @Controller
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
Labels: enhancement

#149 Fix nullpointer in newest-batch-of-machine endpoint
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
  BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
Labels: enhancement

#169 Adds a service to publish to the WebSocket
  BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/ILiveDataService.java
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
  BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataServiceImpl.java
  BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
  BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataServiceImplTest.java
  BrewMesModulesParent/subscriber/pom.xml
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/MachineSubscriber.java
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
Labels: enhancement

#172 code_cleanup
  BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
  BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/MachineSubscriber.java
  BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
  integrationTest/testFiles/collection.json
Labels: enhancement
